version: 2

jobs:
  # Build Website
  doc:
    working_directory: ~/fabric8io/dmp-docs
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - run:
      - git config --global user.email "circleci@fabric8.io"
      - git config --global user.name "CircleCI"
    - run: ./doc/ci-docs.sh

  # Run unit tests
  build:
    working_directory: ~/fabric8io/docker-maven-plugin
    docker:
    - image: circleci/openjdk:8-node-browsers
    steps:
    - checkout
    - restore_cache:
        key: dmp-{{ checksum "pom.xml" }}
    - run: mvn install -Pjacoco
    - run: bash <(curl -s https://codecov.io/bash)
    - save_cache:
        key: dmp-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  sonar-pr:
    working_directory: ~/fabric8io/dmp-sonar-pr
    docker:
    - image: circleci/openjdk:8-node-browsers
    steps:
    - checkout
    - restore_cache:
        key: dmp-sonar-pr-{{ checksum "pom.xml" }}
    - run: |
        if [ -n "${CIRCLE_PR_NUMBER}" ]; then
          mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
             -Dsonar.github.pullRequest=${CIRCLE_PR_NUMBER} \
             -Dsonar.github.repository=fabric8io/docker-maven-plugin \
             -Dsonar.github.oauth=${GITHUB_COMMENT_TOKEN} \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=${SONARQUBE_TOKEN}
        else
          echo "No Sonar PR analysis as this is not a pull request"
        fi

    - save_cache:
        key: dmp-sonar-pr-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  sonar:
    working_directory: ~/fabric8io/dmp-sonar
    docker:
    - image: circleci/openjdk:8-node-browsers
    steps:
    - checkout
    - restore_cache:
        key: dmp-sonar-{{ checksum "pom.xml" }}
    - run: |
        mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${SONARQUBE_TOKEN}
    - save_cache:
        key: dmp-sonar-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

workflows:
  version: 2
  all:
    jobs:
    - doc:
        filters:
          branches:
            only: dmp.fabric8.io
    - build
    - sonar-pr
    - sonar:
        filters:
          branches:
            only: master
